/**
 * docs/spec/payload-vectors.json (change vault-list-labels-archive, task 1.1).
 *
 * The file is generated by scripts/gen-payload-vectors.py (Python). This suite is the
 * independent TypeScript side of the contract:
 *  - a structural check of every section;
 *  - a reference strict canonical codec (docs/spec/payload-v2.md section 5), written from the spec
 *    with JSON.parse / JSON.stringify, that must agree with every positive, negative,
 *    writer and archive-and-clear vector;
 *  - every blob vector is rebuilt with this library and the deterministic replay RNG and
 *    must be byte-identical, then opened with each listed key.
 * The web codec (apps/web, task 1.2) and the Python codec (tools/recover, task 1.3) run the
 * same vectors. Runs in Node and in headless Chromium.
 */
import { describe, expect, it } from 'vitest';
import vectors from '../../../docs/spec/payload-vectors.json' with { type: 'json' };
import { createVault, openVault, updatePayload, type Credential } from '../src/index.js';
import { replayRng } from '../src/testing.js';

const hex = (s: string): Uint8Array => {
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(s.slice(2 * i, 2 * i + 2), 16);
  return out;
};
const toHex = (b: Uint8Array): string => Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');
const utf8 = (s: string): Uint8Array => new Uint8Array(new TextEncoder().encode(s));

// ------------------------------------------------ reference codec (spec section 4-section 7)
type Item = { l: string; s: string };
interface Decoded {
  version: 1 | 2;
  name: string | null;
  archived: boolean;
  items: Item[];
  pad: string | null;
}
class RefError extends Error {
  constructor(readonly code: 'MALFORMED' | 'UNKNOWN_VERSION') {
    super(code);
  }
}
const MALFORMED = (): never => {
  throw new RefError('MALFORMED');
};

const LONE_SURROGATE = /\p{Cs}/u;
// C0, DEL, C1, U+2028/2029, U+202A-202E, U+2066-2069 (spec section 4.3)
const FORBIDDEN_IN_NAME = /[\u0000-\u001f\u007f-\u009f\u2028\u2029\u202a-\u202e\u2066-\u2069]/u;
const cps = (s: string): number => [...s].length;

function validName(n: unknown): n is string {
  return typeof n === 'string' && !LONE_SURROGATE.test(n) && cps(n) >= 1 && cps(n) <= 40 && !FORBIDDEN_IN_NAME.test(n);
}
function validItem(x: unknown): x is Item {
  if (typeof x !== 'object' || x === null || Array.isArray(x)) return false;
  const keys = Object.keys(x);
  if (keys.length !== 2 || keys[0] !== 'l' || keys[1] !== 's') return false;
  const { l, s } = x as Record<string, unknown>;
  return (
    typeof l === 'string' && typeof s === 'string' && !LONE_SURROGATE.test(l) && !LONE_SURROGATE.test(s) && cps(l) <= 64
  );
}

function validate(p: Decoded): void {
  if (!p.items.every(validItem)) MALFORMED();
  if (p.version === 1) {
    if (p.name !== null || p.archived || p.pad !== null || p.items.length === 0) MALFORMED();
    return;
  }
  if (p.name !== null && !validName(p.name)) MALFORMED();
  if (p.pad !== null && (p.items.length !== 0 || !/^0+$/.test(p.pad))) MALFORMED();
}

function encode(p: Decoded): Uint8Array {
  validate(p);
  const wire: Record<string, unknown> = { v: p.version };
  if (p.name !== null) wire.n = p.name;
  if (p.archived) wire.a = true;
  wire.items = p.items.map((i) => ({ l: i.l, s: i.s }));
  if (p.pad !== null) wire.z = p.pad;
  return utf8(JSON.stringify(wire));
}

/** Writer (spec section 6): minimal version. */
function write(p: Omit<Decoded, 'version'>): Uint8Array {
  const v1 = p.name === null && !p.archived && p.pad === null && p.items.length > 0;
  return encode({ ...p, version: v1 ? 1 : 2 });
}

function decode(bytes: Uint8Array): Decoded {
  let text: string;
  try {
    text = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(bytes);
  } catch {
    return MALFORMED();
  }
  const m = /^\{"v":(0|[1-9][0-9]*)[,}]/.exec(text);
  if (m && (m[1]!.length > 1 || m[1]! >= '3')) throw new RefError('UNKNOWN_VERSION');
  let obj: unknown;
  try {
    obj = JSON.parse(text);
  } catch {
    return MALFORMED();
  }
  if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) MALFORMED();
  const o = obj as Record<string, unknown>;
  if (o.v !== 1 && o.v !== 2) MALFORMED();
  const allowed = o.v === 1 ? ['v', 'items'] : ['v', 'n', 'a', 'items', 'z'];
  if (!Object.keys(o).every((k) => allowed.includes(k)) || !Array.isArray(o.items)) MALFORMED();
  if ('n' in o && typeof o.n !== 'string') MALFORMED();
  if ('a' in o && o.a !== true) MALFORMED();
  if ('z' in o && typeof o.z !== 'string') MALFORMED();
  const p: Decoded = {
    version: o.v as 1 | 2,
    name: 'n' in o ? (o.n as string) : null,
    archived: 'a' in o,
    items: o.items as Item[],
    pad: 'z' in o ? (o.z as string) : null,
  };
  const again = encode(p);
  if (toHex(again) !== toHex(bytes)) MALFORMED();
  return { ...p, items: p.items.map((i) => ({ l: i.l, s: i.s })) };
}

/** Archive and clear (spec section 8). */
function clear(previous: Uint8Array, maxPayloadBytes: number): Uint8Array {
  const prev = decode(previous);
  const base = { name: prev.name, archived: true, items: [], pad: null };
  const c0 = write(base).length;
  const p = previous.length;
  let pad: string | null;
  if (p - c0 - 7 >= 1) pad = '0'.repeat(p - c0 - 7);
  else if (c0 >= p) pad = null;
  else if (c0 + 8 <= maxPayloadBytes) pad = '0';
  else pad = null;
  const out = write({ ...base, pad });
  if (out.length > maxPayloadBytes) throw new Error('VAULT_TOO_LARGE');
  return out;
}

const errorOf = (bytes: Uint8Array): string | null => {
  try {
    decode(bytes);
    return null;
  } catch (e) {
    if (e instanceof RefError) return e.code;
    throw e;
  }
};

// ------------------------------------------------------------------ tests
const V = vectors;

describe('payload-vectors.json: structure', () => {
  it('names the spec, the generator and the two error classes', () => {
    expect(V.name).toBe('cryoshield-payload-v2');
    expect(V.spec).toBe('docs/spec/payload-v2.md');
    expect(V.generatedBy).toBe('packages/vault-crypto/scripts/gen-payload-vectors.py');
    expect(V.errorClasses).toEqual(['MALFORMED', 'UNKNOWN_VERSION']);
  });

  it('has unique ids across every section', () => {
    const ids = [...V.positive, ...V.negative, ...V.writer, ...V.archiveClear, ...V.blobs].map((c) => c.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id).toMatch(/^[a-z0-9]+(-[a-z0-9]+)*$/);
  });

  it('covers every case the change requires', () => {
    const neg = new Set(V.negative.map((c) => c.id));
    for (const id of [
      'dup-member-n', 'a-false', 'a-one', 'n-empty', 'n-41-code-points', 'n-bidi-202e', 'n-c0', 'n-c1', 'n-2028',
      'lone-surrogate-escaped', 'extra-member-top', 'whitespace-after-comma', 'member-order-a-before-n',
      'v-string', 'v-3', 'z-non-zero', 'z-with-items', 'v1-empty-items', 'escape-solidus',
    ]) expect(neg, id).toContain(id);
    const pos = new Set(V.positive.map((c) => c.id));
    for (const id of [
      'v1-single', 'v1-multi', 'v1-unicode', 'v2-named', 'v2-archived', 'v2-cleared', 'v2-name-non-bmp',
      'v2-escapes', 'v2-empty-items',
    ]) expect(pos, id).toContain(id);
    expect(V.blobs.length).toBeGreaterThanOrEqual(4);
  });

  it('every hex field is lowercase hex and every text field is its exact UTF-8', () => {
    for (const c of [...V.positive, ...V.negative]) {
      expect(c.hex).toMatch(/^([0-9a-f]{2})*$/);
      if (c.text !== null) expect(toHex(utf8(c.text)), c.id).toBe(c.hex);
    }
  });
});

describe('payload-vectors.json: reference codec agrees', () => {
  it.each(V.positive.map((c) => [c.id, c] as const))('positive %s decodes and re-encodes byte-for-byte', (_id, c) => {
    expect(c.canonicalHex).toBe(c.hex);
    const d = decode(hex(c.hex));
    expect(d).toEqual(c.decoded);
    expect(toHex(encode(d))).toBe(c.hex);
  });

  it.each(V.negative.map((c) => [c.id, c] as const))('negative %s is rejected', (_id, c) => {
    expect(V.errorClasses).toContain(c.error);
    expect(errorOf(hex(c.hex))).toBe(c.error);
    expect(V.positive.some((p) => p.hex === c.hex)).toBe(false);
  });

  it.each(V.writer.map((c) => [c.id, c] as const))('writer %s emits the minimal version', (_id, c) => {
    const out = write(c.input);
    expect(toHex(out)).toBe(c.expectedHex);
    expect(decode(out).version).toBe(c.expectedVersion);
  });

  it.each(V.archiveClear.map((c) => [c.id, c] as const))('archive and clear %s', (_id, c) => {
    const out = clear(hex(c.previousHex), c.maxPayloadBytes);
    expect(toHex(out)).toBe(c.expectedHex);
    expect(out.length).toBe(c.expectedLength);
    expect(out.length).toBeGreaterThanOrEqual(c.previousLength - 7);
    const padLen = (b: number): number => 64 * Math.ceil((2 + b) / 64);
    expect(padLen(out.length)).toBeGreaterThanOrEqual(padLen(c.previousLength));
  });
});

describe('payload-vectors.json: blob vectors regenerate with vault-crypto', () => {
  const allPayloads = new Map<string, string>([
    ...V.positive.map((c) => [c.id, c.hex] as [string, string]),
    ...V.archiveClear.map((c) => [c.id, c.expectedHex] as [string, string]),
  ]);
  const blobs = new Map(V.blobs.map((b) => [b.id, b]));

  it.each(V.blobs.map((b) => [b.id, b] as const))('%s is byte-identical and opens with each key', async (_id, b) => {
    expect(allPayloads.get(b.payloadVector)).toBe(b.payloadHex);
    const vaultId = hex(b.vaultId);
    // The library wipes PRF buffers it is given: build fresh copies for every call.
    const creds = (): Credential[] => b.credentials.map((c) => ({ id: hex(c.id), prf: hex(c.prf) }));
    let blob: Uint8Array;
    if (b.updates === null) {
      const res = await createVault(
        { vaultId, rpId: b.rpId, credentials: creds(), secret: hex(b.payloadHex) },
        { rng: replayRng(hex(b.rng)) },
      );
      blob = res.blob;
    } else {
      const base = blobs.get(b.updates);
      expect(base, b.updates).toBeDefined();
      expect(base!.vaultId).toBe(b.vaultId);
      blob = await updatePayload(hex(base!.blob), { prf: creds()[0]!.prf }, vaultId, hex(b.payloadHex), {
        rng: replayRng(hex(b.rng)),
      });
      if (b.sameLengthAs !== null) expect(blob.length).toBe(hex(blobs.get(b.sameLengthAs)!.blob).length);
    }
    expect(toHex(blob)).toBe(b.blob);
    expect(blob.length).toBe(b.blobLength);
    for (const c of creds()) {
      expect(toHex(await openVault(blob, { prf: c.prf }, vaultId))).toBe(b.payloadHex);
    }
  });
});
