#!/usr/bin/env bash
# Regenerate the measured-gas block of GAS.md from the committed per-call snapshots (snapshots/*.json, written by
# vm.snapshotGasLastCall in test/Gas*.t.sol and test/CryoShieldSmartWallet.t.sol). The snapshots are the source of
# truth; GAS.md must never quote a measured figure outside this block.
#   script/gas-md.sh           rewrite the block in place
#   script/gas-md.sh --check   fail if GAS.md differs from the snapshots, or a snapshot key has no label below
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

BEGIN='<!-- gas-snapshots:begin (generated by script/gas-md.sh from snapshots/*.json; do not edit by hand) -->'
END='<!-- gas-snapshots:end -->'

# One label per snapshot key ("<file>/<key>"). A new snapshot key without a label fails --check.
label() {
  case "$1" in
    VaultRegistry/createVault_1024B_2locators) echo '`createVault`, 1024-byte blob, 2 new locators (full tx)' ;;
    VaultRegistry/updateVault_1024B) echo '`updateVault`, 1024-byte blob replacing a 1024-byte blob (full tx)' ;;
    VaultRegistry/addLocators_1) echo '`addLocators`, 1 new locator (full tx)' ;;
    VaultRegistryV2/createVault_1024B_2locators) echo '`createVault`, 1024-byte blob, 2 new locators (full tx)' ;;
    VaultRegistryV2/updateVault_1024B) echo '`updateVault`, 1024-byte blob (full tx)' ;;
    VaultRegistryV2/addLocators_1) echo '`addLocators`, 1 new locator (full tx; the per-vault duplicate set adds one slot)' ;;
    VaultRegistryV2/resolveLocator_page256) echo '`resolveLocator`, 256-entry page (eth_call)' ;;
    VaultRegistryV2/getVaults_32x1024B) echo '`getVaults`, 32 ids x 1 KB (eth_call, about 36 KB response)' ;;
    CryoShieldSmartWallet/validateUserOp_cryoshield_fclFallback) echo '`validateUserOp`, CryoShieldSmartWallet (our build), software P-256' ;;
    CryoShieldSmartWallet/validateUserOp_cbsw11_fclFallback) echo '`validateUserOp`, Coinbase Smart Wallet v1.1 (deployed bytecode), software P-256' ;;
    *) return 1 ;;
  esac
}

# 1234567 -> 1,234,567 (locale-independent).
commas() { awk '{ n = $0; s = ""; while (length(n) > 3) { s = "," substr(n, length(n) - 2) s; n = substr(n, 1, length(n) - 3) } print n s }' <<<"$1"; }

render() {
  local f group key gas lbl
  echo "$BEGIN"
  for f in snapshots/*.json; do
    group="$(basename "$f" .json)"
    echo
    echo "**${group}** (\`snapshots/${group}.json\`)"
    echo
    echo '| Measurement | Gas |'
    echo '|---|---:|'
    while IFS=$'\t' read -r key gas; do
      lbl="$(label "$group/$key")" || { echo "ERROR: no GAS.md label for snapshot $group/$key (add one to script/gas-md.sh)" >&2; return 1; }
      [[ "$gas" =~ ^[0-9]+$ ]] || { echo "ERROR: $group/$key is not an integer: $gas" >&2; return 1; }
      printf '| %s | %s |\n' "$lbl" "$(commas "$gas")"
    done < <(jq -r 'to_entries | sort_by(.key)[] | "\(.key)\t\(.value)"' "$f")
  done
  echo
  echo "$END"
}

BLOCK="$(render)"
grep -qF "$BEGIN" GAS.md && grep -qF "$END" GAS.md || { echo "ERROR: GAS.md has no generated block markers" >&2; exit 1; }

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
awk -v begin="$BEGIN" -v end="$END" -v blockfile=<(printf '%s\n' "$BLOCK") '
  $0 == begin { while ((getline line < blockfile) > 0) print line; skip = 1; next }
  $0 == end { skip = 0; next }
  !skip { print }
' GAS.md >"$TMP"

if [[ "${1:-}" == "--check" ]]; then
  if diff -u GAS.md "$TMP"; then
    echo "GAS.md matches snapshots/*.json"
  else
    echo "GAS.md is stale: run script/gas-md.sh" >&2
    exit 1
  fi
else
  cp "$TMP" GAS.md
  echo "wrote GAS.md"
fi
