#!/usr/bin/env node
/**
 * Generates the Docker build context for Fly (add-fly-hosting D1/D2):
 *   <out>/site/       = the verified dist/ minus the host-specific `_headers`
 *   <out>/Caddyfile   = static server config; CSP derived from the BUILT index.html meta tag + frame-ancestors 'none'.
 *   Every HTML page (landing index.html, app/index.html) must carry the identical meta CSP, because one header
 *   CSP covers every response (redesign-landing-and-app-ui D8).
 * Usage: node deploy/gen-context.mjs --dist dist --out deploy/.build --host cryoshield.app
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { LANDING_PERMISSIONS_POLICY, SECURITY_HEADERS } from '../vite-plugins/security-headers.ts';

function arg(name) {
  const i = process.argv.indexOf(`--${name}`);
  if (i < 0 || !process.argv[i + 1]) throw new Error(`missing --${name}`);
  return process.argv[i + 1];
}

const dist = arg('dist');
// /release.json is published by release-manifest.mjs at deploy time only; a build must never ship its own.
if (existsSync(join(dist, 'release.json'))) throw new Error(`${dist}/release.json must not be part of the build`);
const out = arg('out');
const host = arg('host');
if (!/^(?=.{1,253}$)([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$/.test(host)) throw new Error(`invalid host: ${host}`);

function pageCsp(rel) {
  const p = join(dist, rel);
  if (!existsSync(p)) throw new Error(`${rel} is missing from the build`);
  const metas = [...readFileSync(p, 'utf8').matchAll(/<meta http-equiv="Content-Security-Policy" content="([^"]+)">/g)];
  if (metas.length !== 1) throw new Error(`${rel} must contain exactly one meta Content-Security-Policy`);
  return metas[0][1];
}
// Per-route CSP (add-privacy-preserving-analytics D3): every page except the landing document carries the identical
// app CSP; the landing CSP may add ONLY the analytics beacon (script-src) and its report origin (connect-src).
const APP_PAGES = ['app/index.html', 'privacy/index.html', 'terms/index.html', 'cookies/index.html', 'architecture/index.html', 'devices/index.html'];
const appMeta = pageCsp('app/index.html');
for (const p of APP_PAGES) {
  if (pageCsp(p) !== appMeta) throw new Error(`the meta CSP of ${p} and app/index.html differ; every non-landing page must carry the app CSP`);
}
const landingMeta = pageCsp('index.html');
const ALLOWED_LANDING_EXTRAS = {
  'script-src': ['https://static.cloudflareinsights.com/beacon.min.js'],
  'connect-src': ['https://cloudflareinsights.com'],
};
const directives = (c) => new Map(c.split(';').map((d) => d.trim()).filter(Boolean).map((d) => { const [k, ...v] = d.split(/\s+/); return [k, v]; }));
{
  const a = directives(appMeta);
  const l = directives(landingMeta);
  for (const k of new Set([...a.keys(), ...l.keys()])) {
    const av = a.get(k) ?? [];
    const lv = l.get(k) ?? [];
    // The landing document may drop connect-src sources (strictly fewer permissions; fix-arweave-mirror-status D4).
    const removed = av.filter((t) => !lv.includes(t) && !(k === 'connect-src' && t !== "'self'"));
    const added = lv.filter((t) => !av.includes(t));
    const bad = added.filter((t) => !(ALLOWED_LANDING_EXTRAS[k] ?? []).includes(t));
    if (removed.length || bad.length || !a.has(k) || !l.has(k)) {
      throw new Error(`the landing CSP differs from the app CSP by more than the allowed analytics sources (${k}: +${bad.join(' ')} -${removed.join(' ')})`);
    }
  }
}
for (const m of [appMeta, landingMeta]) if (/frame-ancestors/.test(m)) throw new Error('meta CSP unexpectedly contains frame-ancestors');
const appCsp = `${appMeta}; frame-ancestors 'none'`;
const landingCsp = `${landingMeta}; frame-ancestors 'none'`;

const quote = (v) => {
  if (v.includes('`')) throw new Error('header value contains a backtick; refusing to quote it into the Caddyfile');
  return `\`${v}\``;
};
const { 'Permissions-Policy': appPermissions, ...common } = SECURITY_HEADERS;
const commonLines = Object.entries(common).map(([k, v]) => `\t\t${k} ${quote(v)}`).join('\n');
const cspLine = (csp) => `\t\tContent-Security-Policy ${quote(csp)}`;
const ppLine = (pp) => `\t\tPermissions-Policy ${quote(pp)}`;
// The RAW request path decides: '/' and '/index.html' only. '//', '/App/', '/%2F' etc. get the app headers.
const LANDING_MATCH = 'expression `{http.request.orig_uri.path} in ["/", "/index.html"]`';
const headerLines = [`\t\tContent-Security-Policy ${quote(appCsp)}`, ...Object.entries(SECURITY_HEADERS).map(([k, v]) => `\t\t${k} ${quote(v)}`)].join('\n');

const caddyfile = `# GENERATED by deploy/gen-context.mjs from the verified build. Do not edit.
{
	admin off
	auto_https off
	persist_config off
}

:8080 {
	header {
		-Server
${commonLines}
	}
	# CSP by the RAW path: only '/' and '/index.html' get the landing CSP (with the analytics sources).
	@landing ${LANDING_MATCH}
	header @landing {
${cspLine(landingCsp)}
	}
	@notlanding not ${LANDING_MATCH}
	header @notlanding {
${cspLine(appCsp)}
	}
	# Permissions-Policy by the NORMALIZED path: anything that serves the landing document ('/', '//', '/index.html')
	# gets no WebAuthn. Stricter wins: e.g. '//' has the app CSP (no beacon can load) AND no WebAuthn.
	@landingdoc path / /index.html
	header @landingdoc {
${ppLine(LANDING_PERMISSIONS_POLICY)}
	}
	@notlandingdoc not path / /index.html
	header @notlandingdoc {
${ppLine(appPermissions)}
	}

	# Every non-canonical Host (www, *.fly.dev, raw IPs, anything else) gets a 301 to the apex. The target host is a
	# constant, and {uri} is always the origin-form path+query, so this can't be abused as an open redirect.
	# /healthz is exempt: Fly's checks reach the machine directly.
	@noncanonical {
		not host ${host}
		not path /healthz
	}
	redir @noncanonical https://${host}{uri} permanent

	handle /healthz {
		header Cache-Control ${quote('no-store')}
		respond "ok" 200
	}

	@html path / /index.html /app/ /app/index.html /privacy /privacy/ /privacy/index.html /terms /terms/ /terms/index.html /cookies /cookies/ /cookies/index.html /architecture /architecture/ /architecture/index.html /devices /devices/ /devices/index.html
	header @html Cache-Control ${quote('no-cache')}

	# Clean URLs for the static legal pages (add-privacy-and-compliance 3.2). Exact paths only: no SPA fallback.
	@legal path /privacy /terms /cookies /architecture /devices
	rewrite @legal {path}/index.html
	# add-brand-icon D4: Go's MIME table has no .webmanifest entry.
	@manifest path /site.webmanifest
	header @manifest Content-Type ${quote('application/manifest+json')}

	# add-continuous-deploy D3: which commit is live. Written at deploy time; never cached.
	@release path /release.json
	header @release Cache-Control ${quote('no-store')}

	@assets path /assets/*
	header @assets Cache-Control ${quote('public, max-age=31536000, immutable')}

	root * /srv
	file_server

	handle_errors {
		header {
			-Server
${headerLines.replace(/^\t\t/gm, '\t\t\t')}
			Cache-Control ${quote('no-store')}
		}
		respond "{err.status_code} {err.status_text}"
	}
}
`;

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(dist, join(out, 'site'), { recursive: true, filter: (src) => !src.endsWith('/_headers') });
if (existsSync(join(out, 'site', '_headers'))) throw new Error('_headers leaked into the site');
writeFileSync(join(out, 'Caddyfile'), caddyfile);
console.log(`wrote ${out}/site and ${out}/Caddyfile for ${host}`);
