#!/usr/bin/env node
/**
 * Generates the Docker build context for Fly (add-fly-hosting D1/D2):
 *   <out>/site/       = the verified dist/ minus the host-specific `_headers`
 *   <out>/Caddyfile   = static server config; CSP derived from the BUILT index.html meta tag + frame-ancestors 'none'.
 *   Every HTML page (landing index.html, app/index.html) must carry the identical meta CSP, because one header
 *   CSP covers every response (redesign-landing-and-app-ui D8).
 * Usage: node deploy/gen-context.mjs --dist dist --out deploy/.build --host cryoshield.app
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SECURITY_HEADERS } from '../vite-plugins/security-headers.ts';

function arg(name) {
  const i = process.argv.indexOf(`--${name}`);
  if (i < 0 || !process.argv[i + 1]) throw new Error(`missing --${name}`);
  return process.argv[i + 1];
}

const dist = arg('dist');
const out = arg('out');
const host = arg('host');
if (!/^(?=.{1,253}$)([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$/.test(host)) throw new Error(`invalid host: ${host}`);

function pageCsp(rel) {
  const p = join(dist, rel);
  if (!existsSync(p)) throw new Error(`${rel} is missing from the build`);
  const metas = [...readFileSync(p, 'utf8').matchAll(/<meta http-equiv="Content-Security-Policy" content="([^"]+)">/g)];
  if (metas.length !== 1) throw new Error(`${rel} must contain exactly one meta Content-Security-Policy`);
  return metas[0][1];
}
const PAGES = ['index.html', 'app/index.html'];
const [meta, ...others] = PAGES.map(pageCsp);
others.forEach((c, i) => {
  if (c !== meta) throw new Error(`the meta CSP of ${PAGES[i + 1]} and index.html differ; one header CSP must cover every page`);
});
if (/frame-ancestors/.test(meta)) throw new Error('meta CSP unexpectedly contains frame-ancestors');
const csp = `${meta}; frame-ancestors 'none'`;

const quote = (v) => {
  if (v.includes('`')) throw new Error('header value contains a backtick; refusing to quote it into the Caddyfile');
  return `\`${v}\``;
};
const headerLines = [
  `\t\tContent-Security-Policy ${quote(csp)}`,
  ...Object.entries(SECURITY_HEADERS).map(([k, v]) => `\t\t${k} ${quote(v)}`),
].join('\n');

const caddyfile = `# GENERATED by deploy/gen-context.mjs from the verified build. Do not edit.
{
	admin off
	auto_https off
	persist_config off
}

:8080 {
	header {
		-Server
${headerLines}
	}

	# Every non-canonical Host (www, *.fly.dev, raw IPs, anything else) gets a 301 to the apex. The target host is a
	# constant, and {uri} is always the origin-form path+query, so this can't be abused as an open redirect.
	# /healthz is exempt: Fly's checks reach the machine directly.
	@noncanonical {
		not host ${host}
		not path /healthz
	}
	redir @noncanonical https://${host}{uri} permanent

	handle /healthz {
		header Cache-Control ${quote('no-store')}
		respond "ok" 200
	}

	@html path / /index.html /app/ /app/index.html
	header @html Cache-Control ${quote('no-cache')}
	@assets path /assets/*
	header @assets Cache-Control ${quote('public, max-age=31536000, immutable')}

	root * /srv
	file_server

	handle_errors {
		header {
			-Server
${headerLines.replace(/^\t\t/gm, '\t\t\t')}
			Cache-Control ${quote('no-store')}
		}
		respond "{err.status_code} {err.status_text}"
	}
}
`;

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(dist, join(out, 'site'), { recursive: true, filter: (src) => !src.endsWith('/_headers') });
if (existsSync(join(out, 'site', '_headers'))) throw new Error('_headers leaked into the site');
writeFileSync(join(out, 'Caddyfile'), caddyfile);
console.log(`wrote ${out}/site and ${out}/Caddyfile for ${host}`);
